In [196]:
import numpy as np
import pandas as pd

In [197]:
matches = pd.read_csv(r"C:\Users\gtshi\Downloads\IPL DASHBOARD\matches.csv")

In [198]:
matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,bat,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,field,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon

In [199]:
deliveries = pd.read_csv(r"C:\Users\gtshi\Downloads\IPL DASHBOARD\deliveries.csv")

In [200]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [201]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [202]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [203]:
matches.dtypes

id                   int64
season                 str
city                   str
date                   str
match_type             str
player_of_match        str
venue                  str
team1                  str
team2                  str
toss_winner            str
toss_decision          str
winner                 str
result                 str
result_margin      float64
target_runs        float64
target_overs       float64
super_over             str
method                 str
umpire1                str
umpire2                str
dtype: object

In [204]:
deliveries.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder'],
      dtype='str')

In [205]:
deliveries.isna()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
1,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True
3,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
4,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
260916,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
260917,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
260918,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True
260919,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,True,True

In [206]:
matches.isnull().sum()

id                    0
season                0
city                 51
date                  0
match_type            0
player_of_match       5
venue                 0
team1                 0
team2                 0
toss_winner           0
toss_decision         0
winner                5
result                0
result_margin        19
target_runs           3
target_overs          3
super_over            0
method             1074
umpire1               0
umpire2               0
dtype: int64

In [207]:
matches["city"].isnull().sum()

np.int64(51)

In [208]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [209]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB

In [210]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1044 non-null   str
 3   date             1095 non-null   str
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: float64(3), int64(1), str(16)
memory usage: 171.2 KB

In [211]:
matches.head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan

In [212]:
matches.shape

(1095, 20)

In [213]:
matches.isnull().sum().sort_values(ascending=False)

method             1074
city                 51
result_margin        19
player_of_match       5
winner                5
target_runs           3
target_overs          3
id                    0
date                  0
season                0
venue                 0
match_type            0
toss_decision         0
toss_winner           0
team2                 0
team1                 0
result                0
super_over            0
umpire1               0
umpire2               0
dtype: int64

In [214]:
matches[['target_runs', 'target_overs']].isnull().sum()

target_runs     3
target_overs    3
dtype: int64

In [215]:
matches[matches['target_runs'].isnull()].head()

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,NaN,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,NaN,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
994,1359519,2023,Lucknow,2023-05-03,League,NaN,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

In [216]:
matches[['winner', 'result']].isnull().sum()

winner    5
result    0
dtype: int64

In [217]:
matches['target_runs'].isnull().sum()

np.int64(3)

In [218]:
matches["date"] = pd.to_datetime(matches["date"])

In [219]:
matches.dtypes

id                          int64
season                        str
city                          str
date               datetime64[us]
match_type                    str
player_of_match               str
venue                         str
team1                         str
team2                         str
toss_winner                   str
toss_decision                 str
winner                        str
result                        str
result_margin             float64
target_runs               float64
target_overs              float64
super_over                    str
method                        str
umpire1                       str
umpire2                       str
dtype: object

In [220]:
matches.loc[matches["city"].isnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
399,729281,2014,NaN,2014-04-17,League,YS Chahal,Sharjah Cricket Stadium,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,8.0,146.0,20.0,N,NaN,Aleem Dar,S Ravi
402,729287,2014,NaN,2014-04-19,League,PA Patel,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,7.0,116.0,20.0,N,NaN,Aleem Dar,AK Chaudhary
403,729289,2014,NaN,2014-04-19,League,JP Duminy,Dubai International Cricket Stadium,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,bat,Delhi Daredevils,wickets,4.0,167.0,20.0,N,NaN,Aleem Dar,VA Kulkarni
404,729291,2014,NaN,2014-04-20,League,GJ Maxwell,Sharjah Cricket Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,7.0,192.0,20.0,N,NaN,BF Bowden,M Erasmus
406,729295,2014,NaN,2014-04-22,League,GJ Maxwell,Sharjah Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,72.0,194.0,20.0,N,NaN,M Erasmus,S Ravi
407,729297,2014,NaN,2014-04-23,League,RA Jadeja,Dubai International Cricket Stadium,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals,field,Chennai Super Kings,runs,7.0,141.0,20.0,N,NaN,HDPK Dharmasena,RK Illingworth
408,729299,2014,NaN,2014-04-24,League,CA Lynn,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,2.0,151.0,20.0,N,NaN,Aleem Dar,VA Kulkarni
409,729301,2014,NaN,2014-04-25,League,AJ Finch,Dubai International Cricket Stadium,Sunrisers Hyderabad,Delhi Daredevils,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,185.0,20.0,N,NaN,M Erasmus,S Ravi
410,729303,2014,NaN,2014-04-25,League,MM Sharma,Dubai International Cricket Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,bat,Chennai Super Kings,wickets,7.0,142.0,20.0,N,NaN,BF Bowden,M Erasmus
413,729309,2014,NaN,2014-04-27,League,M Vijay,Sharjah Cricket Stadium,Delhi Daredevils,Mumbai Indians,Mumbai Indians,bat,Delhi Daredevils,wickets,6.0,126.0,20.0,N,NaN,Aleem Dar,VA Kulkarni
414,729311,2014,NaN,2014-04-27,League,DR Smith,Sharjah Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Chennai Super Kings,wickets,5.0,146.0,20.0,N,NaN,AK Chaudhary,VA Kulkarni
415,729313,2014,NaN,2014-04-28,League,Sandeep Sharma,Dubai International Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab,field,Kings XI Punjab,wickets,5.0,125.0,20.0,N,NaN,BF Bowden,S Ravi
417,729317,2014,NaN,2014-04-30,League,B Kumar,Dubai International Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,15.0,173.0,20.0,N,NaN,HDPK Dharmasena,M Erasmus
757,1216493,2020/21,NaN,2020-09-20,League,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,158.0,20.0,Y,NaN,AK Chaudhary,Nitin Menon
758,1216534,2020/21,NaN,2020-09-21,League,YS Chahal,Dubai International Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,10.0,164.0,20.0,N,NaN,AY Dandekar,Nitin Menon
759,1216496,2020/21,NaN,2020-09-22,League,SV Samson,Sharjah Cricket Stadium,Rajasthan Royals,Chennai Super Kings,Chennai Super Kings,field,Rajasthan Royals,runs,16.0,217.0,20.0,N,NaN,C Shamshuddin,VA Kulkarni
761,1216510,2020/21,NaN,2020-09-24,League,KL Rahul,Dubai International Cricket Stadium,Kings XI Punjab,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Kings XI Punjab,runs,97.0,207.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
762,1216539,2020/21,NaN,2020-09-25,League,PP Shaw,Dubai International Cricket Stadium,Delhi Capitals,Chennai Super Kings,Chennai Super Kings,field,Delhi Capitals,runs,44.0,176.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
764,1216527,2020/21,NaN,2020-09-27,League,SV Samson,Sharjah Cricket Stadium,Kings XI Punjab,Rajasthan Royals,Rajasthan Royals,field,Rajasthan Royals,wickets,4.0,224.0,20.0,N,NaN,RK Illingworth,K Srinivasan
765,1216547,2020/21,NaN,2020-09-28,League,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,202.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
767,1216504,2020/21,NaN,2020-09-30,League,Shivam Mavi,Dubai International Cricket Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,37.0,175.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
769,1216516,2020/21,NaN,2020-10-02,League,PK Garg,Dubai International Cricket Stadium,Sunrisers Hyderabad,Chennai Super Kings,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,7.0,165.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
771,1216515,2020/21,NaN,2020-10-03,League,SS Iyer,Sharjah Cricket Stadium,Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,Delhi Capitals,runs,18.0,229.0,20.0,N,NaN,VA Kulkarni,RK Illingworth
772,1216513,2020/21,NaN,2020-10-04,League,SR Watson,Dubai International Cricket Stadium,Kings XI Punjab,Chennai Super Kings,Kings XI Punjab,bat,Chennai Super Kings,wickets,10.0,179.0,20.0,N,NaN,AY Dandekar,Nitin Menon
773,1216538,2020/21,NaN,2020-10-04,League,TA Boult,Sharjah Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,runs,34.0,209.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
774,1216519,2020/21,NaN,2020-10-05,League,AR Patel,Dubai International Cricket Stadium,Delhi Capitals,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Delhi Capitals,runs,59.0,197.0,20.0,N,NaN,Nitin Menon,YC Barde
777,1216542,2020/21,NaN,2020-10-08,League,JM Bairstow,Dubai International Cricket Stadium,Sunrisers Hyderabad,Kings XI Punjab,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,69.0,202.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
778,1216500,2020/21,NaN,2020-10-09,League,R Ashwin,Sharjah Cricket Stadium,Delhi Capitals,Rajasthan Royals,Rajasthan Royals,field,Delhi Capitals,runs,46.0,185.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
780,1216525,2020/21,NaN,2020-10-10,League,V Kohli,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,37.0,170.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
781,1216507,2020/21,NaN,2020-10-11,League,R Tewatia,Dubai International Cricket Stadium,Sunrisers Hyderabad,Rajasthan Royals,Sunrisers Hyderabad,bat,Rajasthan Royals,wickets,5.0,159.0,20.0,N,NaN,YC Barde,PR Reiffel
783,1216540,2020/21,NaN,2020-10-12,League,AB de Villiers,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,bat,Royal Challengers Bangalore,runs,82.0,195.0,20.0,N,NaN,RK Illingworth,K Srinivasan
784,1216528,2020/21,NaN,2020-10-13,League,RA Jadeja,Dubai International Cricket Stadium,Chennai Super Kings,Sunrisers Hyderabad,Chennai Super Kings,bat,Chennai Super Kings,runs,20.0,168.0,20.0,N,NaN,AK Chaudhary,PR Reiffel
785,1216543,2020/21,NaN,2020-10-14,League,A Nortje,Dubai International Cricket Stadium,Delhi Capitals,Rajasthan Royals,Delhi Capitals,bat,Delhi Capitals,runs,13.0,162.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
786,1216531,2020/21,NaN,2020-10-15,League,KL Rahul,Sharjah Cricket Stadium,Royal Challengers Bangalore,Kings XI Punjab,Royal Challengers Bangalore,bat,Kings XI Punjab,wickets,8.0,172.0,20.0,N,NaN,KN Ananthapadmanabhan,C Shamshuddin
788,1216509,2020/21,NaN,2020-10-17,League,S Dhawan,Sharjah Cricket Stadium,Chennai Super Kings,Delhi Capitals,Chennai Super Kings,bat,Delhi Capitals,wickets,5.0,180.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
789,1216522,2020/21,NaN,2020-10-17,League,AB de Villiers,Dubai International Cricket Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,7.0,178.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
791,1216517,2020/21,NaN,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,177.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
793,1216546,2020/21,NaN,2020-10-20,League,S Dhawan,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Delhi Capitals,bat,Kings XI Punjab,wickets,5.0,165.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
795,1216518,2020/21,NaN,2020-10-22,League,MK Pandey,Dubai International Cricket Stadium,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,155.0,20.0,N,NaN,Nitin Menon,PR Reiffel
796,1216521,2020/21,NaN,2020-10-23,League,TA Boult,Sharjah Cricket Stadium,Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,10.0,115.0,20.0,N,NaN,C Shamshuddin,VA Kulkarni
798,1216498,2020/21,NaN,2020-10-24,League,CJ Jordan,Dubai International Cricket Stadium,Kings XI Punjab,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kings XI Punjab,runs,12.0,127.0,20.0,N,NaN,AY Dandekar,PR Reiffel
800,1216544,2020/21,NaN,2020-10-25,League,RD Gaikwad,Dubai International Cricket Stadium,Royal Challengers Bangalore,Chennai Super Kings,Royal Challengers Bangalore,bat,Chennai Super Kings,wickets,8.0,146.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
801,1216520,2020/21,NaN,2020-10-26,League,CH Gayle,Sharjah Cricket Stadium,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,8.0,150.0,20.0,N,NaN,KN Ananthapadmanabhan,RK Illingworth
802,1216524,2020/21,NaN,2020-10-27,League,WP Saha,Dubai International Cricket Stadium,Sunrisers Hyderabad,Delhi Capitals,Delhi Capitals,field,Sunrisers Hyderabad,runs,88.0,220.0,20.0,N,NaN,AK Chaudhary,Nitin Menon
804,1216536,2020/21,NaN,2020-10-29,League,RD Gaikwad,Dubai International Cricket Stadium,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,6.0,173.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
806,1216502,2020/21,NaN,2020-10-31,League,Sandeep Sharma,Sharjah Cricket Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,5.0,121.0,20.0,N,NaN,KN Ananthapadmanabhan,K Srinivasan
807,1216535,2020/21,NaN,2020-10-31,League,Ishan Kishan,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,9.0,111.0,20.0,N,NaN,YC Barde,PR Reiffel
809,1216530,2020/21,NaN,2020-11-01,League,PJ Cummins,Dubai International Cricket Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,field,Kolkata Knight Riders,runs,60.0,192.0,20.0,N,NaN,Nitin Menon,PR Reiffel
811,1216495,2020/21,NaN,2020-11-03,League,S Nadeem,Sharjah Cricket Stadium,Mumbai Indians,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,10.0,150.0,20.0,N,NaN,C Shamshuddin,RK Illingworth
812,1237177,2020/21,NaN,2020-11-05,Qualifier 1,JJ Bumrah,Dubai International Cricket Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,201.0,20.0,N,NaN,CB Gaffaney,Nitin Menon
815,1237181,2020/21,NaN,2020-11-10,Final,TA Boult,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,157.0,20.0,N,NaN,CB Gaffaney,Nitin Menon

In [221]:
matches[matches['city'].isnull()][['venue', 'city']]

                                   venue city
399              Sharjah Cricket Stadium  NaN
402  Dubai International Cricket Stadium  NaN
403  Dubai International Cricket Stadium  NaN
404              Sharjah Cricket Stadium  NaN
406              Sharjah Cricket Stadium  NaN
407  Dubai International Cricket Stadium  NaN
408              Sharjah Cricket Stadium  NaN
409  Dubai International Cricket Stadium  NaN
410  Dubai International Cricket Stadium  NaN
413              Sharjah Cricket Stadium  NaN
414              Sharjah Cricket Stadium  NaN
415  Dubai International Cricket Stadium  NaN
417  Dubai International Cricket Stadium  NaN
757  Dubai International Cricket Stadium  NaN
758  Dubai International Cricket Stadium  NaN
759              Sharjah Cricket Stadium  NaN
761  Dubai International Cricket Stadium  NaN
762  Dubai International Cricket Stadium  NaN
764              Sharjah Cricket Stadium  NaN
765  Dubai International Cricket Stadium  NaN
767  Dubai International Cricket Stadium  NaN
769  Dubai International Cricket Stadium  NaN
771              Sharjah Cricket Stadium  NaN
772  Dubai International Cricket Stadium  NaN
773              Sharjah Cricket Stadium  NaN
774  Dubai International Cricket Stadium  NaN
777  Dubai International Cricket Stadium  NaN
778              Sharjah Cricket Stadium  NaN
780  Dubai International Cricket Stadium  NaN
781  Dubai International Cricket Stadium  NaN
783              Sharjah Cricket Stadium  NaN
784  Dubai International Cricket Stadium  NaN
785  Dubai International Cricket Stadium  NaN
786              Sharjah Cricket Stadium  NaN
788              Sharjah Cricket Stadium  NaN
789  Dubai International Cricket Stadium  NaN
791  Dubai International Cricket Stadium  NaN
793  Dubai International Cricket Stadium  NaN
795  Dubai International Cricket Stadium  NaN
796              Sharjah Cricket Stadium  NaN
798  Dubai International Cricket Stadium  NaN
800  Dubai International Cricket Stadium  NaN
801              Sharjah Cricket Stadium  NaN
802  Dubai International Cricket Stadium  NaN
804  Dubai International Cricket Stadium  NaN
806              Sharjah Cricket Stadium  NaN
807  Dubai International Cricket Stadium  NaN
809  Dubai International Cricket Stadium  NaN
811              Sharjah Cricket Stadium  NaN
812  Dubai International Cricket Stadium  NaN
815  Dubai International Cricket Stadium  NaN

In [222]:
matches[matches['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium    33
Sharjah Cricket Stadium                18
Name: count, dtype: int64

In [223]:
matches[matches["city"].isnull()]["venue"].unique()

<StringArray>
['Sharjah Cricket Stadium', 'Dubai International Cricket Stadium']
Length: 2, dtype: str

In [224]:
venue_to_city = {
    "Sharjah Cricket Stadium" : "Sharjah",
    "Dubai International Cricket Stadium": "Dubai"
}

In [225]:
matches["city"] = matches["city"].fillna(matches["venue"].map(venue_to_city))

In [226]:
matches["city"].isnull().sum()

np.int64(0)

In [227]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1095 non-null   str
 3   date             1095 non-null   datetime64[us]
 4   match_type       1095 non-null   str
 5   player_of_match  1090 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1090 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: datetime64[us](1), float64(3), int64(1), str(15)
memory usage: 171.2 KB

In [228]:
matches[matches['city'].isnull()]['venue'].value_counts()

Series([], Name: count, dtype: int64)

In [229]:
matches.loc[matches["player_of_match"].isnull(), 
            ["winner", "result", "result_margin", "method"]]

    winner     result  result_margin method
241    NaN  no result            NaN    NaN
485    NaN  no result            NaN    NaN
511    NaN  no result            NaN    NaN
744    NaN  no result            NaN    NaN
994    NaN  no result            NaN    NaN

In [230]:
matches["player_of_match"] = matches["player_of_match"].fillna("No Award")

In [231]:
matches[["player_of_match", "winner"]].isnull().sum()

player_of_match    0
winner             5
dtype: int64

In [232]:
matches[matches["winner"].isnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
241,501265,2011,Delhi,2011-05-21,League,No Award,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,NaN,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
485,829763,2015,Bangalore,2015-04-29,League,No Award,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,No Award,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,NaN,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
744,1178424,2019,Bengaluru,2019-04-30,League,No Award,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,NaN,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
994,1359519,2023,Lucknow,2023-05-03,League,No Award,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,NaN,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

In [233]:
matches["winner"] = matches["winner"].fillna("No Result")

In [234]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1095 non-null   str
 3   date             1095 non-null   datetime64[us]
 4   match_type       1095 non-null   str
 5   player_of_match  1095 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1095 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: datetime64[us](1), float64(3), int64(1), str(15)
memory usage: 171.2 KB

In [235]:
matches[matches["result_margin"].isnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
66,392190,2009,Cape Town,2009-04-23,League,YK Pathan,Newlands,Kolkata Knight Riders,Rajasthan Royals,Kolkata Knight Riders,field,Rajasthan Royals,tie,NaN,151.0,20.0,Y,NaN,MR Benson,M Erasmus
130,419121,2009/10,Chennai,2010-03-21,League,J Theron,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,field,Kings XI Punjab,tie,NaN,137.0,20.0,Y,NaN,K Hariharan,DJ Harper
241,501265,2011,Delhi,2011-05-21,League,No Award,Feroz Shah Kotla,Delhi Daredevils,Pune Warriors,Delhi Daredevils,bat,No Result,no result,NaN,NaN,NaN,N,NaN,SS Hazare,RJ Tucker
328,598004,2013,Hyderabad,2013-04-07,League,GH Vihari,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,bat,Sunrisers Hyderabad,tie,NaN,131.0,20.0,Y,NaN,AK Chaudhary,S Ravi
342,598017,2013,Bangalore,2013-04-16,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,Royal Challengers Bangalore,tie,NaN,153.0,20.0,Y,NaN,M Erasmus,VA Kulkarni
416,729315,2014,Abu Dhabi,2014-04-29,League,JP Faulkner,Sheikh Zayed Stadium,Kolkata Knight Riders,Rajasthan Royals,Rajasthan Royals,bat,Rajasthan Royals,tie,NaN,153.0,20.0,Y,NaN,Aleem Dar,AK Chaudhary
475,829741,2015,Ahmedabad,2015-04-21,League,SE Marsh,"Sardar Patel Stadium, Motera",Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,tie,NaN,192.0,20.0,Y,NaN,M Erasmus,S Ravi
485,829763,2015,Bangalore,2015-04-29,League,No Award,M Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,No Result,no result,NaN,NaN,NaN,N,NaN,JD Cloete,PG Pathak
511,829813,2015,Bangalore,2015-05-17,League,No Award,M Chinnaswamy Stadium,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,field,No Result,no result,NaN,188.0,20.0,N,NaN,HDPK Dharmasena,K Srinivasan
610,1082625,2017,Rajkot,2017-04-29,League,KH Pandya,Saurashtra Cricket Association Stadium,Gujarat Lions,Mumbai Indians,Gujarat Lions,bat,Mumbai Indians,tie,NaN,154.0,20.0,Y,NaN,AK Chaudhary,CB Gaffaney
705,1175365,2019,Delhi,2019-03-30,League,PP Shaw,Arun Jaitley Stadium,Kolkata Knight Riders,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,tie,NaN,186.0,20.0,Y,NaN,AY Dandekar,Nitin Menon
744,1178424,2019,Bengaluru,2019-04-30,League,No Award,M.Chinnaswamy Stadium,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals,field,No Result,no result,NaN,63.0,5.0,N,NaN,NJ Llong,UV Gandhe
746,1178426,2019,Mumbai,2019-05-02,League,JJ Bumrah,Wankhede Stadium,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,bat,Mumbai Indians,tie,NaN,163.0,20.0,Y,NaN,CK Nandan,S Ravi
757,1216493,2020/21,Dubai,2020-09-20,League,MP Stoinis,Dubai International Cricket Stadium,Delhi Capitals,Kings XI Punjab,Kings XI Punjab,field,Delhi Capitals,tie,NaN,158.0,20.0,Y,NaN,AK Chaudhary,Nitin Menon
765,1216547,2020/21,Dubai,2020-09-28,League,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,202.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
790,1216512,2020/21,Abu Dhabi,2020-10-18,League,LH Ferguson,Sheikh Zayed Stadium,Kolkata Knight Riders,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Kolkata Knight Riders,tie,NaN,164.0,20.0,Y,NaN,PG Pathak,S Ravi
791,1216517,2020/21,Dubai,2020-10-18,League,KL Rahul,Dubai International Cricket Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,bat,Kings XI Punjab,tie,NaN,177.0,20.0,Y,NaN,Nitin Menon,PR Reiffel
835,1254077,2021,Chennai,2021-04-25,League,PP Shaw,"MA Chidambaram Stadium, Chepauk, Chennai",Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,tie,NaN,160.0,20.0,Y,NaN,CB Gaffaney,KN Ananthapadmanabhan
994,1359519,2023,Lucknow,2023-05-03,League,No Award,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Chennai Super Kings,Chennai Super Kings,field,No Result,no result,NaN,NaN,NaN,N,NaN,AK Chaudhary,NA Patwardhan

In [236]:
matches[matches['result_margin'].isnull()][
    ['result', 'super_over']
].value_counts()

result     super_over
tie        Y             14
no result  N              5
Name: count, dtype: int64

In [237]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1095 non-null   str
 3   date             1095 non-null   datetime64[us]
 4   match_type       1095 non-null   str
 5   player_of_match  1095 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1095 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
dtypes: datetime64[us](1), float64(3), int64(1), str(15)
memory usage: 171.2 KB

In [238]:
matches[matches["method"].notnull()]

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2
38,336022,2007/08,Delhi,2008-05-17,League,DPMD Jayawardene,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,bat,Kings XI Punjab,runs,6.0,89.0,8.0,N,D/L,AV Jayaprakash,RE Koertzen
41,336025,2007/08,Kolkata,2008-05-18,League,M Ntini,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,Chennai Super Kings,runs,3.0,53.0,8.0,N,D/L,Asad Rauf,K Hariharan
60,392183,2009,Cape Town,2009-04-19,League,DL Vettori,Newlands,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,field,Delhi Daredevils,wickets,10.0,54.0,6.0,N,D/L,MR Benson,SD Ranade
63,392186,2009,Durban,2009-04-21,League,CH Gayle,Kingsmead,Kings XI Punjab,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,runs,11.0,69.0,9.2,N,D/L,DJ Harper,SD Ranade
89,392214,2009,Centurion,2009-05-07,League,ML Hayden,SuperSport Park,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings,bat,Chennai Super Kings,runs,12.0,187.0,18.0,N,D/L,DJ Harper,TH Wijewardene
192,501215,2011,Kochi,2011-04-18,League,BB McCullum,Nehru Stadium,Kochi Tuskers Kerala,Chennai Super Kings,Kochi Tuskers Kerala,field,Kochi Tuskers Kerala,wickets,7.0,135.0,17.0,N,D/L,K Hariharan,AL Hill
221,501245,2011,Kolkata,2011-05-07,League,Iqbal Abdulla,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Chennai Super Kings,bat,Kolkata Knight Riders,runs,10.0,52.0,10.0,N,D/L,Asad Rauf,PR Reiffel
231,501255,2011,Bangalore,2011-05-14,League,CH Gayle,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Royal Challengers Bangalore,wickets,4.0,102.0,13.0,N,D/L,RE Koertzen,RB Tiffin
429,733993,2014,Delhi,2014-05-10,League,DW Steyn,Feroz Shah Kotla,Delhi Daredevils,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,8.0,43.0,5.0,N,D/L,RM Deshpande,BNJ Oxenford
476,829743,2015,Visakhapatnam,2015-04-22,League,DA Warner,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Sunrisers Hyderabad,runs,16.0,118.0,12.0,N,D/L,RK Illingworth,VA Kulkarni
508,829807,2015,Hyderabad,2015-05-15,League,V Kohli,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,Royal Challengers Bangalore,wickets,6.0,81.0,6.0,N,D/L,AK Chaudhary,HDPK Dharmasena
538,980943,2016,Hyderabad,2016-04-26,League,AB Dinda,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Rising Pune Supergiants,Rising Pune Supergiants,field,Rising Pune Supergiants,runs,34.0,61.0,11.0,N,D/L,AY Dandekar,CK Nandan
561,980989,2016,Kolkata,2016-05-14,League,YK Pathan,Eden Gardens,Kolkata Knight Riders,Rising Pune Supergiants,Rising Pune Supergiants,bat,Kolkata Knight Riders,wickets,8.0,66.0,9.0,N,D/L,A Nand Kishore,BNJ Oxenford
565,980997,2016,Visakhapatnam,2016-05-17,League,AB Dinda,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Rising Pune Supergiants,Delhi Daredevils,Rising Pune Supergiants,field,Rising Pune Supergiants,runs,19.0,58.0,11.0,N,D/L,Nitin Menon,C Shamshuddin
566,980999,2016,Bangalore,2016-05-18,League,V Kohli,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab,field,Royal Challengers Bangalore,runs,82.0,203.0,14.0,N,D/L,KN Ananthapadmanabhan,M Erasmus
633,1082648,2017,Bangalore,2017-05-17,Eliminator,NM Coulter-Nile,M Chinnaswamy Stadium,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,7.0,48.0,6.0,N,D/L,AK Chaudhary,Nitin Menon
641,1136566,2018,Jaipur,2018-04-11,League,SV Samson,Sawai Mansingh Stadium,Rajasthan Royals,Delhi Daredevils,Delhi Daredevils,field,Rajasthan Royals,runs,10.0,71.0,6.0,N,D/L,KN Ananthapadmanabhan,Nitin Menon
653,1136578,2018,Kolkata,2018-04-21,League,KL Rahul,Eden Gardens,Kolkata Knight Riders,Kings XI Punjab,Kings XI Punjab,field,Kings XI Punjab,wickets,9.0,125.0,13.0,N,D/L,A Deshmukh,C Shamshuddin
667,1136592,2018,Delhi,2018-05-02,League,RR Pant,Arun Jaitley Stadium,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,field,Delhi Daredevils,runs,4.0,151.0,12.0,N,D/L,CK Nandan,VK Sharma
951,1359476,2023,Chandigarh,2023-04-01,League,Arshdeep Singh,"Punjab Cricket Association IS Bindra Stadium, ...",Punjab Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,Punjab Kings,runs,7.0,154.0,16.0,N,D/L,BNJ Oxenford,YC Barde
1023,1370353,2023,Ahmedabad,2023-05-29,Final,DP Conway,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Chennai Super Kings,Chennai Super Kings,field,Chennai Super Kings,wickets,5.0,171.0,15.0,N,D/L,Nitin Menon,RJ Tucker

In [239]:
matches['is_dl'] = matches['method'].notnull()

In [240]:
matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,Chennai Super Kings,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,False
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,Delhi Daredevils,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,False
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,Royal Challengers Bangalore,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,False
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,Kolkata Knight Riders,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,Sunrisers Hyderabad,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma,False
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Kolkata Knight Riders,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit,False
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,Rajasthan Royals,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,False
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,Sunrisers Hyderabad,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma,False
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False

In [241]:
matches['has_margin'] = matches['result_margin'].notnull()

In [242]:
matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,False,True
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,False,True
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,False,True
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma,False,True
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit,False,True
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,False,True
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma,False,True
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [243]:
matches.info()

<class 'pandas.DataFrame'>
RangeIndex: 1095 entries, 0 to 1094
Data columns (total 22 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               1095 non-null   int64
 1   season           1095 non-null   str
 2   city             1095 non-null   str
 3   date             1095 non-null   datetime64[us]
 4   match_type       1095 non-null   str
 5   player_of_match  1095 non-null   str
 6   venue            1095 non-null   str
 7   team1            1095 non-null   str
 8   team2            1095 non-null   str
 9   toss_winner      1095 non-null   str
 10  toss_decision    1095 non-null   str
 11  winner           1095 non-null   str
 12  result           1095 non-null   str
 13  result_margin    1076 non-null   float64
 14  target_runs      1092 non-null   float64
 15  target_overs     1092 non-null   float64
 16  super_over       1095 non-null   str
 17  method           21 non-null     str
 18  umpire1          1095 non-null   str
 19  umpire2          1095 non-null   str
 20  is_dl            1095 non-null   bool
 21  has_margin       1095 non-null   bool
dtypes: bool(2), datetime64[us](1), float64(3), int64(1), str(15)
memory usage: 173.4 KB

In [244]:
matches[matches['target_runs'].isnull()][
    ['result', 'super_over', 'method']
]

        result super_over method
241  no result          N    NaN
485  no result          N    NaN
994  no result          N    NaN

In [245]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [246]:
deliveries.info()

<class 'pandas.DataFrame'>
RangeIndex: 260920 entries, 0 to 260919
Data columns (total 17 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   match_id          260920 non-null  int64
 1   inning            260920 non-null  int64
 2   batting_team      260920 non-null  str
 3   bowling_team      260920 non-null  str
 4   over              260920 non-null  int64
 5   ball              260920 non-null  int64
 6   batter            260920 non-null  str
 7   bowler            260920 non-null  str
 8   non_striker       260920 non-null  str
 9   batsman_runs      260920 non-null  int64
 10  extra_runs        260920 non-null  int64
 11  total_runs        260920 non-null  int64
 12  extras_type       14125 non-null   str
 13  is_wicket         260920 non-null  int64
 14  player_dismissed  12950 non-null   str
 15  dismissal_kind    12950 non-null   str
 16  fielder           9354 non-null    str
dtypes: int64(8), str(9)
memory usage: 33.8 MB

In [247]:
deliveries.isnull().sum().sort_values(ascending=False)

fielder             251566
dismissal_kind      247970
player_dismissed    247970
extras_type         246795
match_id                 0
inning                   0
batting_team             0
bowling_team             0
over                     0
non_striker              0
bowler                   0
batter                   0
ball                     0
total_runs               0
extra_runs               0
batsman_runs             0
is_wicket                0
dtype: int64

In [248]:
deliveries[deliveries["extras_type"].notnull()]

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,1,1,legbyes,0,NaN,NaN,NaN
15,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,2,3,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
19,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,3,1,BB McCullum,AA Noffke,SC Ganguly,0,5,5,wides,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260873,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,3,1,Rahmanullah Gurbaz,T Natarajan,VR Iyer,0,1,1,wides,0,NaN,NaN,NaN
260876,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,3,4,Rahmanullah Gurbaz,T Natarajan,VR Iyer,0,1,1,wides,0,NaN,NaN,NaN
260894,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,6,2,Rahmanullah Gurbaz,Shahbaz Ahmed,VR Iyer,0,4,4,byes,0,NaN,NaN,NaN
260897,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,6,5,VR Iyer,Shahbaz Ahmed,Rahmanullah Gurbaz,0,1,1,legbyes,0,NaN,NaN,NaN
260906,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,8,2,VR Iyer,Shahbaz Ahmed,Rahmanullah Gurbaz,0,1,1,legbyes,0,NaN,NaN,NaN

In [249]:
deliveries.head()

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN

In [250]:
deliveries["total_runs"] = deliveries["batsman_runs"] + deliveries["extra_runs"]

In [251]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [252]:
df = deliveries.merge(matches, left_on = "match_id", right_on = "id")

In [253]:
df.head(10)

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
5,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,6,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
6,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,7,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
7,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,1,BB McCullum,Z Khan,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
8,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,2,BB McCullum,Z Khan,SC Ganguly,4,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
9,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,1,3,BB McCullum,Z Khan,SC Ganguly,4,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True

In [254]:
df.shape

(260920, 39)

In [255]:
top_batsman = df.groupby("batter")["batsman_runs"].sum().sort_values(ascending=False).head(10)

In [256]:
top_batsman

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
MS Dhoni          5243
AB de Villiers    5181
CH Gayle          4997
RV Uthappa        4954
KD Karthik        4843
Name: batsman_runs, dtype: int64

In [257]:
top_batsman.head(5)

batter
V Kohli      8014
S Dhawan     6769
RG Sharma    6630
DA Warner    6567
SK Raina     5536
Name: batsman_runs, dtype: int64

In [258]:
top_batsman.dtype

dtype('int64')

In [259]:
del top_batsman

In [260]:
top_batsman

NameError: name 'top_batsman' is not defined

In [261]:
top_batsmen = df.groupby("batter")["batsman_runs"].sum().sort_values(ascending=False).head(10)

In [262]:
top_batsmen

batter
V Kohli           8014
S Dhawan          6769
RG Sharma         6630
DA Warner         6567
SK Raina          5536
MS Dhoni          5243
AB de Villiers    5181
CH Gayle          4997
RV Uthappa        4954
KD Karthik        4843
Name: batsman_runs, dtype: int64

In [263]:
top_batsmen.head(5)

batter
V Kohli      8014
S Dhawan     6769
RG Sharma    6630
DA Warner    6567
SK Raina     5536
Name: batsman_runs, dtype: int64

In [264]:
balls_faced = df.groupby("batter")["ball"].count()

In [265]:
balls_faced["batter"] = ["Virat Kohli"]

In [266]:
balls_faced = balls_faced.drop("batter")

In [267]:
balls_faced

batter
A Ashish Reddy     196
A Badoni           505
A Chandila           7
A Chopra            75
A Choudhary         20
                  ...
Yashpal Singh       67
Younis Khan          7
Yudhvir Singh       16
Yuvraj Singh      2207
Z Khan             141
Name: ball, Length: 673, dtype: object

In [268]:
valid_batters = balls_faced[balls_faced > 1000].index

In [269]:
valid_batters

Index(['AB de Villiers', 'AC Gilchrist', 'AD Russell', 'AJ Finch', 'AM Rahane',
       'AR Patel', 'AT Rayudu', 'BB McCullum', 'BJ Hodge', 'CH Gayle',
       'D Padikkal', 'DA Miller', 'DA Warner', 'DJ Bravo', 'DJ Hooda',
       'DJ Hussey', 'DPMD Jayawardene', 'DR Smith', 'EJG Morgan',
       'F du Plessis', 'G Gambhir', 'GJ Maxwell', 'HH Pandya', 'Ishan Kishan',
       'JC Buttler', 'JH Kallis', 'JM Bairstow', 'JP Duminy', 'KA Pollard',
       'KC Sangakkara', 'KD Karthik', 'KH Pandya', 'KK Nair', 'KL Rahul',
       'KM Jadhav', 'KS Williamson', 'M Vijay', 'MA Agarwal', 'MEK Hussey',
       'MK Pandey', 'MK Tiwary', 'MP Stoinis', 'MS Dhoni', 'Mandeep Singh',
       'N Pooran', 'N Rana', 'NV Ojha', 'PA Patel', 'PP Shaw', 'Q de Kock',
       'R Dravid', 'RA Jadeja', 'RA Tripathi', 'RD Gaikwad', 'RG Sharma',
       'RR Pant', 'RV Uthappa', 'S Badrinath', 'S Dhawan', 'S Dube',
       'SA Yadav', 'SC Ganguly', 'SE Marsh', 'SK Raina', 'SPD Smith',
       'SR Tendulkar', 'SR Watson', 'SS Iyer', 'SS Tiwary', 'SV Samson',
       'Shubman Gill', 'TM Dilshan', 'V Kohli', 'V Sehwag', 'WP Saha',
       'YBK Jaiswal', 'YK Pathan', 'Yuvraj Singh'],
      dtype='str', name='batter')

In [270]:
df_filtered = df[df['batter'].isin(valid_batters)]

In [271]:
df_filtered

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260763,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,4,1,RA Tripathi,MA Starc,AK Markram,0,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260764,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,4,2,RA Tripathi,MA Starc,AK Markram,0,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260910,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,8,6,SS Iyer,Shahbaz Ahmed,VR Iyer,4,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [272]:
# Getting Individual Scores by the Batsman

runs = df_filtered.groupby("batter")["batsman_runs"].sum()

In [273]:
runs

batter
AB de Villiers    5181
AC Gilchrist      2069
AD Russell        2488
AJ Finch          2092
AM Rahane         4642
                  ...
V Sehwag          2728
WP Saha           2934
YBK Jaiswal       1607
YK Pathan         3222
Yuvraj Singh      2754
Name: batsman_runs, Length: 78, dtype: int64

In [274]:
# Calculating Balls Faced By the Batsman

balls = df_filtered.groupby("batter")["ball"].count()

In [275]:
balls

batter
AB de Villiers    3487
AC Gilchrist      1555
AD Russell        1515
AJ Finch          1696
AM Rahane         3858
                  ...
V Sehwag          1833
WP Saha           2368
YBK Jaiswal       1095
YK Pathan         2334
Yuvraj Singh      2207
Name: ball, Length: 78, dtype: int64

In [276]:
# Calculated the strike rate using the formula

strike_rate = ((runs / balls) *100).round(2)

In [277]:
strike_rate

batter
AB de Villiers    148.58
AC Gilchrist      133.05
AD Russell        164.22
AJ Finch          123.35
AM Rahane         120.32
                   ...
V Sehwag          148.83
WP Saha           123.90
YBK Jaiswal       146.76
YK Pathan         138.05
Yuvraj Singh      124.78
Length: 78, dtype: float64

In [278]:
# Returning Top 10 Aggressive Batsmen

top_strike_rate = strike_rate.sort_values(ascending=False).head(10)

In [279]:
top_strike_rate

batter
AD Russell        164.22
N Pooran          154.77
GJ Maxwell        150.49
V Sehwag          148.83
AB de Villiers    148.58
YBK Jaiswal       146.76
RR Pant           143.60
PP Shaw           143.22
SA Yadav          142.51
JC Buttler        142.24
dtype: float64

In [280]:
top_strike_rate.head(5)

batter
AD Russell        164.22
N Pooran          154.77
GJ Maxwell        150.49
V Sehwag          148.83
AB de Villiers    148.58
dtype: float64

In [281]:
analysis = pd.DataFrame({
    'runs': runs,
    'balls': balls,
    'strike_rate': strike_rate
})

In [282]:
analysis = analysis.sort_values(by='runs', ascending=False)
analysis.head(10)

                runs  balls  strike_rate
batter
V Kohli         8014   6236       128.51
S Dhawan        6769   5483       123.45
RG Sharma       6630   5183       127.92
DA Warner       6567   4849       135.43
SK Raina        5536   4177       132.54
MS Dhoni        5243   3947       132.84
AB de Villiers  5181   3487       148.58
CH Gayle        4997   3516       142.12
RV Uthappa      4954   3927       126.15
KD Karthik      4843   3687       131.35

In [283]:
analysis.sort_values(by=['runs', 'strike_rate'], ascending=False).head(10)

                runs  balls  strike_rate
batter
V Kohli         8014   6236       128.51
S Dhawan        6769   5483       123.45
RG Sharma       6630   5183       127.92
DA Warner       6567   4849       135.43
SK Raina        5536   4177       132.54
MS Dhoni        5243   3947       132.84
AB de Villiers  5181   3487       148.58
CH Gayle        4997   3516       142.12
RV Uthappa      4954   3927       126.15
KD Karthik      4843   3687       131.35

In [284]:
analysis['performance_score'] = analysis['runs'] * analysis['strike_rate']

In [285]:
analysis.sort_values(by='performance_score', ascending=False).head(10)

                runs  balls  strike_rate  performance_score
batter
V Kohli         8014   6236       128.51         1029879.14
DA Warner       6567   4849       135.43          889368.81
RG Sharma       6630   5183       127.92          848109.60
S Dhawan        6769   5483       123.45          835633.05
AB de Villiers  5181   3487       148.58          769792.98
SK Raina        5536   4177       132.54          733741.44
CH Gayle        4997   3516       142.12          710173.64
MS Dhoni        5243   3947       132.84          696480.12
KD Karthik      4843   3687       131.35          636128.05
RV Uthappa      4954   3927       126.15          624947.10

In [294]:
analysis['normalized_runs'] = analysis['runs'] / analysis['runs'].max()
analysis['normalized_sr'] = analysis['strike_rate'] / analysis['strike_rate'].max()

analysis['balanced_score'] = analysis['normalized_runs'] * analysis['normalized_sr']

In [295]:
analysis.sort_values(by='balanced_score', ascending=False).head(10)

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score
batter,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951
AB de Villiers,5181,3487,148.58,769792.98,0.646494,0.904762,0.584923
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529
CH Gayle,4997,3516,142.12,710173.64,0.623534,0.865424,0.539621
MS Dhoni,5243,3947,132.84,696480.12,0.654230,0.808915,0.529216
KD Karthik,4843,3687,131.35,636128.05,0.604317,0.799842,0.483358
RV Uthappa,4954,3927,126.15,624947.10,0.618168,0.768177,0.474862

In [288]:
print(analysis)

            runs  balls  strike_rate  performance_score  normalized_runs  \
batter
V Kohli     8014   6236       128.51         1029879.14         1.000000
S Dhawan    6769   5483       123.45          835633.05         0.844647
RG Sharma   6630   5183       127.92          848109.60         0.827302
DA Warner   6567   4849       135.43          889368.81         0.819441
SK Raina    5536   4177       132.54          733741.44         0.690791
...          ...    ...          ...                ...              ...
BJ Hodge    1400   1153       121.42          169988.00         0.174694
SC Ganguly  1349   1326       101.73          137233.77         0.168330
DJ Hussey   1322   1101       120.07          158732.54         0.164961
KM Jadhav   1208   1012       119.37          144198.96         0.150736
TM Dilshan  1153   1047       110.12          126968.36         0.143873

            normalized_sr  balanced_score
batter
V Kohli          0.782548        0.782548
S Dhawan         0.751735        0.634951
RG Sharma        0.778955        0.644431
DA Warner        0.824686        0.675782
SK Raina         0.807088        0.557529
...                   ...             ...
BJ Hodge         0.739374        0.129164
SC Ganguly       0.619474        0.104276
DJ Hussey        0.731153        0.120612
KM Jadhav        0.726891        0.109569
TM Dilshan       0.670564        0.096476

[78 rows x 7 columns]

In [289]:
deliveries

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN

In [290]:
matches

,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335983,2007/08,Chandigarh,2008-04-19,League,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,...,runs,33.0,241.0,20.0,N,NaN,MR Benson,SL Shastri,False,True
2,335984,2007/08,Delhi,2008-04-19,League,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,...,wickets,9.0,130.0,20.0,N,NaN,Aleem Dar,GA Pratapkumar,False,True
3,335985,2007/08,Mumbai,2008-04-20,League,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,...,wickets,5.0,166.0,20.0,N,NaN,SJ Davis,DJ Harper,False,True
4,335986,2007/08,Kolkata,2008-04-20,League,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,...,wickets,5.0,111.0,20.0,N,NaN,BF Bowden,K Hariharan,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1090,1426307,2024,Hyderabad,2024-05-19,League,Abhishek Sharma,"Rajiv Gandhi International Stadium, Uppal, Hyd...",Punjab Kings,Sunrisers Hyderabad,Punjab Kings,...,wickets,4.0,215.0,20.0,N,NaN,Nitin Menon,VK Sharma,False,True
1091,1426309,2024,Ahmedabad,2024-05-21,Qualifier 1,MA Starc,"Narendra Modi Stadium, Ahmedabad",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,wickets,8.0,160.0,20.0,N,NaN,AK Chaudhary,R Pandit,False,True
1092,1426310,2024,Ahmedabad,2024-05-22,Eliminator,R Ashwin,"Narendra Modi Stadium, Ahmedabad",Royal Challengers Bengaluru,Rajasthan Royals,Rajasthan Royals,...,wickets,4.0,173.0,20.0,N,NaN,KN Ananthapadmanabhan,MV Saidharshan Kumar,False,True
1093,1426311,2024,Chennai,2024-05-24,Qualifier 2,Shahbaz Ahmed,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Rajasthan Royals,Rajasthan Royals,...,runs,36.0,176.0,20.0,N,NaN,Nitin Menon,VK Sharma,False,True
1094,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [291]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,...,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,...,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,...,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [296]:
analysis['balanced_score_v2'] = (
    normalized_runs + normalized_sr
) / 2

NameError: name 'normalized_runs' is not defined

In [297]:
analysis['normalized_runs'] = analysis['runs'] / analysis['runs'].max()
analysis['normalized_sr'] = analysis['strike_rate'] / analysis['strike_rate'].max()

In [298]:
analysis['balanced_score_v2'] = (
    analysis['normalized_runs'] + analysis['normalized_sr']
) / 2

In [299]:
analysis.sort_values(by='balanced_score_v2', ascending=False).head(5)

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2
batter,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191
AB de Villiers,5181,3487,148.58,769792.98,0.646494,0.904762,0.584923,0.775628

In [300]:
df_wins = df[df['batting_team'] == df['winner']]

In [316]:
df_wins

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [313]:
df_wins.shape

(127485, 39)

In [315]:
pd.set_option('display.max_columns', None)

In [317]:
df.columns

Index(['match_id', 'inning', 'batting_team', 'bowling_team', 'over', 'ball',
       'batter', 'bowler', 'non_striker', 'batsman_runs', 'extra_runs',
       'total_runs', 'extras_type', 'is_wicket', 'player_dismissed',
       'dismissal_kind', 'fielder', 'id', 'season', 'city', 'date',
       'match_type', 'player_of_match', 'venue', 'team1', 'team2',
       'toss_winner', 'toss_decision', 'winner', 'result', 'result_margin',
       'target_runs', 'target_overs', 'super_over', 'method', 'umpire1',
       'umpire2', 'is_dl', 'has_margin'],
      dtype='str')

In [318]:
df[['batting_team', 'winner']].head()

            batting_team                 winner
0  Kolkata Knight Riders  Kolkata Knight Riders
1  Kolkata Knight Riders  Kolkata Knight Riders
2  Kolkata Knight Riders  Kolkata Knight Riders
3  Kolkata Knight Riders  Kolkata Knight Riders
4  Kolkata Knight Riders  Kolkata Knight Riders

In [319]:
df_wins = df[df['batting_team'] == df['winner']]

In [320]:
df_wins.shape

(127485, 39)

In [321]:
winning_runs = df_wins.groupby("batter")["batsman_runs"].sum()

In [325]:
winning_runs.sort_values(ascending=False).head(5)

batter
V Kohli      4278
S Dhawan     3989
RG Sharma    3951
DA Warner    3710
SK Raina     3559
Name: batsman_runs, dtype: int64

In [327]:
analysis["winning_runs"]  = winning_runs

In [329]:
analysis

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs
batter,,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274,4278
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191,3989
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129,3951
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064,3710
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559
...,...,...,...,...,...,...,...,...,...
BJ Hodge,1400,1153,121.42,169988.00,0.174694,0.739374,0.129164,0.457034,632
SC Ganguly,1349,1326,101.73,137233.77,0.168330,0.619474,0.104276,0.393902,678
DJ Hussey,1322,1101,120.07,158732.54,0.164961,0.731153,0.120612,0.448057,554
KM Jadhav,1208,1012,119.37,144198.96,0.150736,0.726891,0.109569,0.438813,385
TM Dilshan,1153,1047,110.12,126968.36,0.143873,0.670564,0.096476,0.407219,795

In [330]:
analysis['winning_ratio'] = analysis['winning_runs'] / analysis['runs']

In [336]:
analysis_filtered = analysis[analysis['runs'] > 2000]

In [337]:
analysis_filtered.sort_values(by="winning_ratio", ascending=False).head(5)

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio
batter,,,,,,,,,,
Shubman Gill,3216,2432,132.24,425283.84,0.401298,0.805261,0.323150,0.603279,2254,0.700871
RD Gaikwad,2380,1781,133.63,318039.40,0.296980,0.813725,0.241660,0.555353,1614,0.678151
G Gambhir,4217,3524,119.67,504648.39,0.526204,0.728718,0.383454,0.627461,2839,0.673227
V Sehwag,2728,1833,148.83,406008.24,0.340404,0.906284,0.308503,0.623344,1807,0.662390
DR Smith,2385,1803,132.28,315487.80,0.297604,0.805505,0.239722,0.551555,1546,0.648218

In [338]:
analysis_filtered.sort_values(
    by=['winning_ratio', 'runs'],
    ascending=[False, False]
).head(10)

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio
batter,,,,,,,,,,
Shubman Gill,3216,2432,132.24,425283.84,0.401298,0.805261,0.323150,0.603279,2254,0.700871
RD Gaikwad,2380,1781,133.63,318039.40,0.296980,0.813725,0.241660,0.555353,1614,0.678151
G Gambhir,4217,3524,119.67,504648.39,0.526204,0.728718,0.383454,0.627461,2839,0.673227
V Sehwag,2728,1833,148.83,406008.24,0.340404,0.906284,0.308503,0.623344,1807,0.662390
DR Smith,2385,1803,132.28,315487.80,0.297604,0.805505,0.239722,0.551555,1546,0.648218
SR Tendulkar,2334,2044,114.19,266519.46,0.291240,0.695348,0.202513,0.493294,1507,0.645673
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559,0.642883
CH Gayle,4997,3516,142.12,710173.64,0.623534,0.865424,0.539621,0.744479,3162,0.632780
SR Watson,3880,2892,134.16,520540.80,0.484153,0.816953,0.395530,0.650553,2431,0.626546
BB McCullum,2882,2272,126.85,365581.70,0.359621,0.772439,0.277785,0.566030,1800,0.624566

In [339]:
analysis_filtered['impact_score'] = (
    0.5 * analysis_filtered['winning_ratio'] +
    0.5 * (analysis_filtered['runs'] / analysis_filtered['runs'].max())
)

In [340]:
analysis_filtered.sort_values(by='impact_score', ascending=False).head(10)

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio,impact_score
batter,,,,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274,4278,0.533816,0.766908
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191,3989,0.589304,0.716976
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129,3951,0.595928,0.711615
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064,3710,0.564946,0.692193
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559,0.642883,0.666837
CH Gayle,4997,3516,142.12,710173.64,0.623534,0.865424,0.539621,0.744479,3162,0.632780,0.628157
AB de Villiers,5181,3487,148.58,769792.98,0.646494,0.904762,0.584923,0.775628,3080,0.594480,0.620487
MS Dhoni,5243,3947,132.84,696480.12,0.654230,0.808915,0.529216,0.731572,3007,0.573527,0.613878
G Gambhir,4217,3524,119.67,504648.39,0.526204,0.728718,0.383454,0.627461,2839,0.673227,0.599716
F du Plessis,4571,3435,133.07,608262.97,0.570377,0.810315,0.462185,0.690346,2751,0.601838,0.586107

In [341]:
df

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
0,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,1,SC Ganguly,P Kumar,BB McCullum,0,1,1,legbyes,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
1,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,2,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
2,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,3,BB McCullum,P Kumar,SC Ganguly,0,1,1,wides,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
3,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,4,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
4,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,0,5,BB McCullum,P Kumar,SC Ganguly,0,0,0,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260915,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,5,SS Iyer,AK Markram,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260916,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,9,6,VR Iyer,AK Markram,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260917,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,1,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260918,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,2,SS Iyer,Shahbaz Ahmed,VR Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260919,1426312,2,Kolkata Knight Riders,Sunrisers Hyderabad,10,3,VR Iyer,Shahbaz Ahmed,SS Iyer,1,0,1,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [342]:
# Death Overs Performance

death_overs = df[df["over"]>=16]

In [343]:
death_overs

,match_id,inning,batting_team,bowling_team,over,ball,batter,bowler,non_striker,batsman_runs,extra_runs,total_runs,extras_type,is_wicket,player_dismissed,dismissal_kind,fielder,id,season,city,date,match_type,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,target_runs,target_overs,super_over,method,umpire1,umpire2,is_dl,has_margin
100,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,1,BB McCullum,Z Khan,DJ Hussey,1,0,1,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
101,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,2,DJ Hussey,Z Khan,BB McCullum,2,0,2,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
102,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,3,DJ Hussey,Z Khan,BB McCullum,1,0,1,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
103,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,4,BB McCullum,Z Khan,DJ Hussey,6,0,6,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
104,335982,1,Kolkata Knight Riders,Royal Challengers Bangalore,16,5,BB McCullum,Z Khan,DJ Hussey,2,0,2,NaN,0,NaN,NaN,NaN,335982,2007/08,Bangalore,2008-04-18,League,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,223.0,20.0,N,NaN,Asad Rauf,RE Koertzen,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
260848,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,5,JD Unadkat,SP Narine,PJ Cummins,0,0,0,NaN,1,JD Unadkat,lbw,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260849,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,17,6,B Kumar,SP Narine,PJ Cummins,0,0,0,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260850,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,1,PJ Cummins,AD Russell,B Kumar,0,0,0,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260851,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,2,PJ Cummins,AD Russell,B Kumar,0,0,0,NaN,0,NaN,NaN,NaN,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True
260852,1426312,1,Sunrisers Hyderabad,Kolkata Knight Riders,18,3,PJ Cummins,AD Russell,B Kumar,0,0,0,NaN,1,PJ Cummins,caught,MA Starc,1426312,2024,Chennai,2024-05-26,Final,MA Starc,"MA Chidambaram Stadium, Chepauk, Chennai",Sunrisers Hyderabad,Kolkata Knight Riders,Sunrisers Hyderabad,bat,Kolkata Knight Riders,wickets,8.0,114.0,20.0,N,NaN,J Madanagopal,Nitin Menon,False,True

In [350]:
#  Runs scored in death overs by Batters
death_runs = death_overs.groupby("batter")["batsman_runs"].sum()

In [351]:
# Balls faced by batters in death overs
death_balls = death_overs.groupby("batter")["ball"].count()

In [352]:
# Batsmen strike rate in death overs 

death_sr = (( death_runs / death_balls ) * 100 ).round(2)

In [353]:
death_sr

batter
A Ashish Reddy    148.84
A Badoni          156.60
A Chandila         57.14
A Choudhary       126.32
A Dananjaya        80.00
                   ...
Yash Dayal          0.00
Yashpal Singh     110.00
Yudhvir Singh      33.33
Yuvraj Singh      165.11
Z Khan            103.06
Length: 583, dtype: float64

In [355]:
death_analysis = pd.DataFrame ({
    "runs" : death_runs,
    "balls" : death_balls,
    "strike_rate" : death_sr
})

In [356]:
death_analysis

                runs  balls  strike_rate
batter
A Ashish Reddy   192    129       148.84
A Badoni         332    212       156.60
A Chandila         4      7        57.14
A Choudhary       24     19       126.32
A Dananjaya        4      5        80.00
...              ...    ...          ...
Yash Dayal         0      1         0.00
Yashpal Singh     11     10       110.00
Yudhvir Singh      1      3        33.33
Yuvraj Singh     601    364       165.11
Z Khan           101     98       103.06

[583 rows x 3 columns]

In [357]:
death_analysis = death_analysis[death_analysis["balls"]>200]

In [361]:
death_analysis.sort_values(by='strike_rate', ascending=False).head(10)

                runs  balls  strike_rate
batter
AB de Villiers  1421    635       223.78
RR Pant          626    318       196.86
CH Gayle         404    209       193.30
V Kohli         1099    571       192.47
F du Plessis     416    220       189.09
RG Sharma       1176    625       188.16
SA Yadav         516    276       186.96
AD Russell      1065    570       186.84
TH David         452    244       185.25
SO Hetmyer       680    368       184.78

In [362]:
death_analysis.sort_values(by='strike_rate', ascending=False).head(5)

                runs  balls  strike_rate
batter
AB de Villiers  1421    635       223.78
RR Pant          626    318       196.86
CH Gayle         404    209       193.30
V Kohli         1099    571       192.47
F du Plessis     416    220       189.09

In [363]:
analysis['death_sr'] = death_sr

In [364]:
analysis

,runs,balls,strike_rate,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio,death_sr
batter,,,,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274,4278,0.533816,192.47
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191,3989,0.589304,160.97
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129,3951,0.595928,188.16
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064,3710,0.564946,174.37
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559,0.642883,163.95
...,...,...,...,...,...,...,...,...,...,...,...
BJ Hodge,1400,1153,121.42,169988.00,0.174694,0.739374,0.129164,0.457034,632,0.451429,161.97
SC Ganguly,1349,1326,101.73,137233.77,0.168330,0.619474,0.104276,0.393902,678,0.502595,160.56
DJ Hussey,1322,1101,120.07,158732.54,0.164961,0.731153,0.120612,0.448057,554,0.419062,172.05
KM Jadhav,1208,1012,119.37,144198.96,0.150736,0.726891,0.109569,0.438813,385,0.318709,137.87
TM Dilshan,1153,1047,110.12,126968.36,0.143873,0.670564,0.096476,0.407219,795,0.689506,172.34

In [368]:
final_analysis = analysis.merge(death_analysis[['strike_rate']], 
                                left_index=True, 
                                right_index=True, 
                                how='left')

In [369]:
final_analysis

,runs,balls,strike_rate_x,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio,death_sr,strike_rate_y
batter,,,,,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274,4278,0.533816,192.47,192.47
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191,3989,0.589304,160.97,160.97
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129,3951,0.595928,188.16,188.16
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064,3710,0.564946,174.37,174.37
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559,0.642883,163.95,163.95
...,...,...,...,...,...,...,...,...,...,...,...,...
BJ Hodge,1400,1153,121.42,169988.00,0.174694,0.739374,0.129164,0.457034,632,0.451429,161.97,161.97
SC Ganguly,1349,1326,101.73,137233.77,0.168330,0.619474,0.104276,0.393902,678,0.502595,160.56,NaN
DJ Hussey,1322,1101,120.07,158732.54,0.164961,0.731153,0.120612,0.448057,554,0.419062,172.05,NaN
KM Jadhav,1208,1012,119.37,144198.96,0.150736,0.726891,0.109569,0.438813,385,0.318709,137.87,137.87
TM Dilshan,1153,1047,110.12,126968.36,0.143873,0.670564,0.096476,0.407219,795,0.689506,172.34,NaN

In [ ]:
final_analysis.sort_values(
    by=['impact_score', 'strike_rate'], 
    ascending=False
).head(10)

In [370]:
final_analysis.columns

Index(['runs', 'balls', 'strike_rate_x', 'performance_score',
       'normalized_runs', 'normalized_sr', 'balanced_score',
       'balanced_score_v2', 'winning_runs', 'winning_ratio', 'death_sr',
       'strike_rate_y'],
      dtype='str')

In [371]:
final_analysis = final_analysis.rename(columns={
    'strike_rate_x': 'overall_sr',
    'strike_rate_y': 'death_sr'
})

KeyError: 'strike_rate_y'

In [376]:
final_analysis['impact_score'] = (
    0.5 * final_analysis['winning_ratio'] +
    0.5 * (final_analysis['runs'] / final_analysis['runs'].max())
)

In [377]:
final_analysis.sort_values(
    by=['impact_score', 'strike_rate_y'],
    ascending=False
).head(10)

KeyError: 'strike_rate_y'

In [378]:
final_analysis

,runs,balls,overall_sr,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio,death_sr,death_sr,impact_score
batter,,,,,,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274,4278,0.533816,192.47,192.47,0.766908
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191,3989,0.589304,160.97,160.97,0.716976
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129,3951,0.595928,188.16,188.16,0.711615
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064,3710,0.564946,174.37,174.37,0.692193
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559,0.642883,163.95,163.95,0.666837
...,...,...,...,...,...,...,...,...,...,...,...,...,...
BJ Hodge,1400,1153,121.42,169988.00,0.174694,0.739374,0.129164,0.457034,632,0.451429,161.97,161.97,0.313061
SC Ganguly,1349,1326,101.73,137233.77,0.168330,0.619474,0.104276,0.393902,678,0.502595,160.56,NaN,0.335462
DJ Hussey,1322,1101,120.07,158732.54,0.164961,0.731153,0.120612,0.448057,554,0.419062,172.05,NaN,0.292012
KM Jadhav,1208,1012,119.37,144198.96,0.150736,0.726891,0.109569,0.438813,385,0.318709,137.87,137.87,0.234722
TM Dilshan,1153,1047,110.12,126968.36,0.143873,0.670564,0.096476,0.407219,795,0.689506,172.34,NaN,0.416689

In [379]:
final_analysis.columns

Index(['runs', 'balls', 'overall_sr', 'performance_score', 'normalized_runs',
       'normalized_sr', 'balanced_score', 'balanced_score_v2', 'winning_runs',
       'winning_ratio', 'death_sr', 'death_sr', 'impact_score'],
      dtype='str')

In [382]:
final_analysis.columns.duplicated()

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [381]:
final_analysis = final_analysis.loc[:, ~final_analysis.columns.duplicated()]

In [383]:
final_analysis.sort_values(
    by=['impact_score', 'death_sr'],
    ascending=False
).head(10)

,runs,balls,overall_sr,performance_score,normalized_runs,normalized_sr,balanced_score,balanced_score_v2,winning_runs,winning_ratio,death_sr,impact_score
batter,,,,,,,,,,,,
V Kohli,8014,6236,128.51,1029879.14,1.000000,0.782548,0.782548,0.891274,4278,0.533816,192.47,0.766908
S Dhawan,6769,5483,123.45,835633.05,0.844647,0.751735,0.634951,0.798191,3989,0.589304,160.97,0.716976
RG Sharma,6630,5183,127.92,848109.60,0.827302,0.778955,0.644431,0.803129,3951,0.595928,188.16,0.711615
DA Warner,6567,4849,135.43,889368.81,0.819441,0.824686,0.675782,0.822064,3710,0.564946,174.37,0.692193
SK Raina,5536,4177,132.54,733741.44,0.690791,0.807088,0.557529,0.748940,3559,0.642883,163.95,0.666837
CH Gayle,4997,3516,142.12,710173.64,0.623534,0.865424,0.539621,0.744479,3162,0.632780,193.30,0.628157
AB de Villiers,5181,3487,148.58,769792.98,0.646494,0.904762,0.584923,0.775628,3080,0.594480,223.78,0.620487
MS Dhoni,5243,3947,132.84,696480.12,0.654230,0.808915,0.529216,0.731572,3007,0.573527,179.05,0.613878
G Gambhir,4217,3524,119.67,504648.39,0.526204,0.728718,0.383454,0.627461,2839,0.673227,135.43,0.599716
F du Plessis,4571,3435,133.07,608262.97,0.570377,0.810315,0.462185,0.690346,2751,0.601838,189.09,0.586107